### ISSUE TITLE
Animation for units when they are dealing/taking damage (Sprint 4)

### ISSUE THREAD

**Issue by wtchou712** [wtchou712/Morty-Defense#8]
Possibly a bounce back animation

**Comment by wtchou712** [comment]
http://answers.unity3d.com/questions/796881/c-how-can-i-let-something-happen-after-a-small-del.html

**Comment by wtchou712** [comment]
Enemies currently bounce back only.

**Comment by tedwu13** [comment]
Add a POW or a dust cloud

**Comment by wtchou712** [comment]
Added flash animation when units collide
